### ISSUE TITLE
Transform not generating JavaScript code from peg grammar

### ISSUE THREAD

**Issue by panzerdp** [rstone770/pegify#1]
Hi @rstone770 
Nice transform library.
I have a problem when my grammar is not transformed to JavaScript source. I get the error: `Fatal error: Expected code block, comment, end of line, identifier or whitespace but "\"" found.`
It works fine when using the online generator: http://pegjs.org/online.

Also, could you include `pegjs` as a dependency in `package.json` (I don't have pegjs globally installed).
Thanks.

**Comment by rstone770** [comment]
You do not need to install pegjs globally, just installed alongside each other.

```
npm install pegify pegjs
```

I do not want to add it as a dependency because I do not want to have to maintain versions parallel to pegjs.

As for your grammar, it's hard to see what the issue is without the productions in question and your test strings. I will be reworking the transform, so i can take a look to make sure i'm not adding anything weird to the string before it's parsed.
